dist: xenial

services:
  - mysql

matrix:
  include:
    - name: "Redmine 3.4"
      env:
        - REDMINE_VERSION=3.4-stable
      install:
        - gem install bundler -v "1.17.3"
        - bundle _1.17.3_ install
        - bin/rake db:create
        - bin/rake generate_secret_token
        - bin/rake db:migrate
        - bin/rake redmine:plugins:migrate
      script:
        - RAILS_ENV=test bin/rake redmine:plugins:test:integration

before_install:
  - cd ..
  - git clone
      --depth 1
      --branch ${REDMINE_VERSION}
      https://github.com/redmine/redmine.git
  - cd redmine/plugins
  - ln -s ../../redmine_exception_handler ./
  - cd ../
  - cp config/database.yml{.example,}
  - unset BUNDLE_GEMFILE
